### ISSUE TITLE
[BUG] An error is thrown when logging->location to 1  All display items cannot be displayed

### ISSUE THREAD

**Issue by AdminHcat** [PotatoCraft-Studio/QuickShop-Reremake#107]
### Description

`[12:22:25 INFO]: [QuickShop] Enabling QuickShop v5.1.0.4-SNAPSHOT
[12:22:25 INFO]: [QuickShop] QuickShop Reremake
[12:22:25 INFO]: [QuickShop] Starting plugin self-test, please wait...
[12:22:25 INFO]: [QuickShop] [OK] Signature Verify
[12:22:25 INFO]: [QuickShop] [OK] Plugin Manifest Check
[12:22:25 INFO]: [QuickShop] [OK] Potential Infection Characteristics Check
[12:22:25 INFO]: [QuickShop] [OK] Java Runtime Environment Version Test
[12:22:25 INFO]: [QuickShop] Running QuickShop-Reremake on NMS version v1_18_R1 For Minecraft version 1.18.1
[12:22:25 INFO]: [QuickShop] [OK] Spigot Based Server Test
[12:22:25 INFO]: [QuickShop] [OK] Old QuickShop Test
[12:22:25 INFO]: [QuickShop] [OK] ModdedServer Based Test
[12:22:25 INFO]: [QuickShop] [OK] CoreSupport Test
[12:22:25 INFO]: [QuickShop] [OK] Virtual DisplayItem Support Test
[12:22:25 INFO]: [QuickShop] [OK] GameVersion supporting Test
[12:22:25 INFO]: [QuickShop] [OK] PacketListenerAPI Conflict Test
[12:22:25 INFO]: [QuickShop] [OK] Permission Manager Test
[12:22:25 INFO]: [QuickShop] [OK] End of life Test
[12:22:25 INFO]: [QuickShop] Reading the configuration...
[12:22:25 INFO]: [QuickShop] Developers: PotatoCraft Studio, Netherfoam, Timtower, KaiNoMood (KaiKikuchi), jho5245, Ghost_chu, cakoyo, Ectabro, portlek, log4b0at, Andre601, deadman96385, Vlvxingze, DoctaEnkoda, Mgazul, TiaraRinne, sandtechnology, Starmism, Chris6ix, Rean Schwarzer, mart-r, raphtaliapt, Tim269, creatorfromhell, LoneDev6, judgetread, confuxeon, ibmibmibm, yannicklamprecht, PyvesB, PaulBGD, ORelio, JoschuaSchneider, Starmium, harry0198
[12:22:25 INFO]: [QuickShop] Original author: Netherfoam, Timtower, KaiNoMood
[12:22:25 INFO]: [QuickShop] Let's start loading the plugin
[12:22:25 INFO]: [QuickShop] Chat processor selected: Hardcoded BungeeChat Lib
[12:22:25 INFO]: [QuickShop] Loading plugin translations files...
[12:22:25 INFO]: [QuickShop] Game assets server selected: BMCLAPI
[12:22:25 INFO]: [QuickShop] ===Mirror description===
[12:22:25 INFO]: [QuickShop] BMCLAPI is a non-profit mirror service made by @bangbang93 to speed up download in China mainland region.
[12:22:25 INFO]: [QuickShop] Donate BMCLAPI or get details about BMCLAPI, check here: https://bmclapidoc.bangbang93.com
[12:22:25 INFO]: [QuickShop] You should only use this mirror if your server in China mainland or have connection trouble with Mojang server, otherwise use Mojang Official server
[12:22:25 WARN]: [QuickShop] You're selected unofficial game assets server, use at your own risk.
[12:22:25 INFO]: [QuickShop] Loading items translations...
[12:22:26 INFO]: [QuickShop] Loading enchantments translations...
[12:22:26 INFO]: [QuickShop] Loading potions translations...
[12:22:26 INFO]: [QuickShop] Successfully loaded OpenInv support!
[12:22:26 INFO]: [QuickShop] Successfully loaded PlaceHolderAPI support!
[12:22:26 INFO]: [QuickShop] Successfully loaded WorldEdit support!
[12:22:26 INFO]: [QuickShop] Registering NoCheatPlus Compatibility Module
[12:22:26 INFO]: [QuickShop] Using Virtual Item display, loading ProtocolLib support...
[12:22:26 INFO]: [QuickShop] Successfully loaded ProtocolLib support!
[12:22:26 INFO]: [QuickShop] Setting up database...
[12:22:26 INFO]: [QuickShop] Checking and updating database columns, it may take a while...
[12:22:26 INFO]: [QuickShop] Finished!
[12:22:26 INFO]: [QuickShop] Selected permission provider: Bukkit
[12:22:26 INFO]: [QuickShop] Registering commands...
[12:22:26 WARN]: Failed to load player data for a49f2732-f199-3f05-b437-f7cc7905cd07
[12:22:26 INFO]: [QuickShop] Loaded 1 rules for listener blacklist.
[12:22:26 INFO]: [QuickShop] EventManager selected: QSEventManager
[12:22:26 INFO]: [QuickShop] Fetching shops from the database...If plugin stuck there, check your database connection.
[12:22:26 INFO]: [QuickShop] Loading shops from the database...
[12:22:26 WARN]: [QuickShop] Failed load shop data, because target config can't deserialize the ItemStack
org.bukkit.configuration.InvalidConfigurationException: Exception in deserialize item
	at org.maxgamer.quickshop.util.Util.deserialize(Util.java:368) ~[QuickShop-5.1.0.4-SNAPSHOT.jar:?]
	at org.maxgamer.quickshop.shop.ShopLoader$ShopDatabaseInfo.deserializeItem(ShopLoader.java:456) ~[QuickShop-5.1.0.4-SNAPSHOT.jar:?]
	at org.maxgamer.quickshop.shop.ShopLoader$ShopDatabaseInfo.<init>(ShopLoader.java:444) ~[QuickShop-5.1.0.4-SNAPSHOT.jar:?]
	at org.maxgamer.quickshop.shop.ShopLoader.loadShops(ShopLoader.java:112) ~[QuickShop-5.1.0.4-SNAPSHOT.jar:?]
	at org.maxgamer.quickshop.shop.ShopLoader.loadShops(ShopLoader.java:81) ~[QuickShop-5.1.0.4-SNAPSHOT.jar:?]
	at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:960) ~[QuickShop-5.1.0.4-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[purpur-1.18.1.jar:git-Purpur-1555]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[purpur-1.18.1.jar:git-Purpur-1555]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:732) ~[purpur-1.18.1.jar:git-Purpur-1555]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:508) ~[purpur-1.18.1.jar:git-Purpur-1555]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:349) ~[purpur-1.18.1.jar:git-Purpur-1555]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[purpur-1.18.1.jar:git-Purpur-1555]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1555]
	at net.minecraft.server.MinecraftServer$$Lambda$3966/0x00000000275ae230.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Thread.java:884) ~[?:?]
Caused by: org.yaml.snakeyaml.error.YAMLException: Could not deserialize object
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:50) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[snakeyaml-1.30.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:39) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[snakeyaml-1.30.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:39) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
	at org.bukkit.configuration.file.YamlConstructor.construct(YamlConstructor.java:27) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:158) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:115) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.maxgamer.quickshop.util.Util.deserialize(Util.java:365) ~[QuickShop-5.1.0.4-SNAPSHOT.jar:?]
	... 17 more
Caused by: java.lang.IllegalArgumentException: Specified class does not exist ('com.destroystokyo.paper.profile.CraftPlayerProfile')
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:197) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:48) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[snakeyaml-1.30.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:39) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[snakeyaml-1.30.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:39) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
	at org.bukkit.configuration.file.YamlConstructor.construct(YamlConstructor.java:27) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:158) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:115) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.maxgamer.quickshop.util.Util.deserialize(Util.java:365) ~[QuickShop-5.1.0.4-SNAPSHOT.jar:?]
	... 17 more
[12:22:26 WARN]: [QuickShop] ##########FAILED TO LOAD SHOP##########
[12:22:26 WARN]: [QuickShop]   >> Error Info:
[12:22:26 WARN]: [QuickShop] Cannot invoke "org.bukkit.inventory.ItemStack.clone()" because "item" is null
[12:22:26 WARN]: [QuickShop]   >> Error Trace
[12:22:26 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.clone()" because "item" is null
[12:22:26 WARN]: 	at QuickShop-5.1.0.4-SNAPSHOT.jar//org.maxgamer.quickshop.shop.ContainerShop.<init>(ContainerShop.java:165)
[12:22:26 WARN]: 	at QuickShop-5.1.0.4-SNAPSHOT.jar//org.maxgamer.quickshop.shop.ShopLoader.loadShops(ShopLoader.java:133)
[12:22:26 WARN]: 	at QuickShop-5.1.0.4-SNAPSHOT.jar//org.maxgamer.quickshop.shop.ShopLoader.loadShops(ShopLoader.java:81)
[12:22:26 WARN]: 	at QuickShop-5.1.0.4-SNAPSHOT.jar//org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:960)
[12:22:26 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[12:22:26 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[12:22:26 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[12:22:26 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[12:22:26 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[12:22:26 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:732)
[12:22:26 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:508)
[12:22:26 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:349)
[12:22:26 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1218)
[12:22:26 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[12:22:26 WARN]: 	at net.minecraft.server.MinecraftServer$$Lambda$3966/0x00000000275ae230.run(Unknown Source)
[12:22:26 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:884)
[12:22:26 WARN]: [QuickShop]   >> Target Location Info
[12:22:26 WARN]: [QuickShop] Location: NULL
[12:22:26 WARN]: [QuickShop] Block: NULL
[12:22:26 WARN]: [QuickShop] #######################################
[12:22:26 INFO]: [QuickShop] Registering listeners...
[12:22:26 INFO]: [QuickShop] Cleaning MsgUtils...
[12:22:26 INFO]: [QuickShop] Cleaning purchase messages from the database that are over a week old...
[12:22:26 INFO]: [QuickShop] Log actions is enabled, actions will log in the qs.log file!
[12:22:26 INFO]: [QuickShop] [Shop Purger] Purge not enabled!
[12:22:26 INFO]: [QuickShop] QuickShop Loaded! 782 ms.
[12:22:26 INFO]: [QuickShop] Using economy system: EssentialsX Economy
[12:22:26 INFO]: [ProtectionLib] Enabling ProtectionLib v1.4
[12:22:26 INFO]: [ProtectionLib] ProtectionLib-Module: LocalLibary hooked!`

### Steps to reproduce

Set logging->location to 1

![image](https://user-images.githubusercontent.com/50044729/153904292-d9cf6903-79a8-4d27-970b-aacd01e16eb5.png)

### Expected Behaviour

All display items can displayed

### Screenshots

![image](https://user-images.githubusercontent.com/50044729/153905513-e2cd7750-391c-41ed-b5a6-79e8fd692582.png)

### `/qs paste` URL

https://paste.helpch.at/ogujivicuh

### Additional Context

When I set logging->location back to 0, they will recover and no longer report errors

**Comment by sandtechnology** [comment]
It's not cause by our plugin but the server software, related issue: https://github.com/PaperMC/Paper/issues/7470
Please update to the latest purpur to fix it.
