### ISSUE TITLE
[BUG] Some shops in the server failed

### ISSUE THREAD

**Issue by Pen92he** [PotatoCraft-Studio/QuickShop-Reremake#110]
### Description

Whenever I restart the server Will make some stores of the server ineffective

### Steps to reproduce

1

### Expected Behaviour

1

### Screenshots

1

### `/qs paste` URL

https://github.com/PotatoCraft-Studio/QuickShop-Reremake/wiki/Migrate:-v4-to-v5

### Additional Context

[12:38:51] [Server thread/WARN]: [QuickShop] Failed load shop data, because target config can't deserialize the ItemStack
org.bukkit.configuration.InvalidConfigurationException: Exception in deserialize item
	at org.maxgamer.quickshop.util.Util.deserialize(Util.java:368) ~[[快捷商店]QuickShop-5.1.0.4.jar:?]
	at org.maxgamer.quickshop.shop.ShopLoader$ShopDatabaseInfo.deserializeItem(ShopLoader.java:456) ~[[快捷商店]QuickShop-5.1.0.4.jar:?]
	at org.maxgamer.quickshop.shop.ShopLoader$ShopDatabaseInfo.<init>(ShopLoader.java:444) ~[[快捷商店]QuickShop-5.1.0.4.jar:?]
	at org.maxgamer.quickshop.shop.ShopLoader.loadShops(ShopLoader.java:112) ~[[快捷商店]QuickShop-5.1.0.4.jar:?]
	at org.maxgamer.quickshop.shop.ShopLoader.loadShops(ShopLoader.java:81) ~[[快捷商店]QuickShop-5.1.0.4.jar:?]
	at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:960) ~[[快捷商店]QuickShop-5.1.0.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[purpur-1.18.1.jar:git-Purpur-1533]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[purpur-1.18.1.jar:git-Purpur-1533]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:732) ~[purpur-1.18.1.jar:git-Purpur-1533]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:508) ~[purpur-1.18.1.jar:git-Purpur-1533]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:349) ~[purpur-1.18.1.jar:git-Purpur-1533]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[purpur-1.18.1.jar:git-Purpur-1533]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1533]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.yaml.snakeyaml.error.YAMLException: Could not deserialize object
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:50) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[snakeyaml-1.30.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:39) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[snakeyaml-1.30.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:39) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
	at org.bukkit.configuration.file.YamlConstructor.construct(YamlConstructor.java:27) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:158) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:115) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.maxgamer.quickshop.util.Util.deserialize(Util.java:365) ~[[快捷商店]QuickShop-5.1.0.4.jar:?]
	... 16 more

**Comment by sandtechnology** [comment]
Look like is duplicated by #107 , please update purpur to the latest version and try again

**Comment by Pen92he** [comment]
in fact. The problem is that I returned this version to the latest version of. Pur after I updated it I tried to reduce quickshop back to 5.10.3. It seems that the problem has been solved

**Comment by sandtechnology** [comment]
Also please provide the full error

**Comment by Pen92he** [comment]
[12:38:49] [Server thread/INFO]: [QuickShop] Enabling QuickShop v5.1.0.4
[12:38:49] [Server thread/INFO]: [QuickShop] QuickShop Reremake
[12:38:49] [Server thread/INFO]: [QuickShop] Starting plugin self-test, please wait...
[12:38:49] [Server thread/INFO]: [QuickShop] [OK] Signature Verify
[12:38:49] [Server thread/INFO]: [QuickShop] [OK] Plugin Manifest Check
[12:38:49] [Server thread/INFO]: [QuickShop] [OK] Potential Infection Characteristics Check
[12:38:49] [Server thread/INFO]: [QuickShop] [OK] Java Runtime Environment Version Test
[12:38:49] [Server thread/INFO]: [QuickShop] Running QuickShop-Reremake on NMS version v1_18_R1 For Minecraft version 1.18.1
[12:38:49] [Server thread/INFO]: [QuickShop] [OK] Spigot Based Server Test
[12:38:49] [Server thread/INFO]: [QuickShop] [OK] Old QuickShop Test
[12:38:49] [Server thread/INFO]: [QuickShop] [OK] ModdedServer Based Test
[12:38:49] [Server thread/INFO]: [QuickShop] [OK] CoreSupport Test
[12:38:49] [Server thread/INFO]: [QuickShop] [OK] Virtual DisplayItem Support Test
[12:38:49] [Server thread/INFO]: [QuickShop] [OK] GameVersion supporting Test
[12:38:49] [Server thread/INFO]: [QuickShop] [OK] Permission Manager Test
[12:38:49] [Server thread/INFO]: [QuickShop] [OK] PacketListenerAPI Conflict Test
[12:38:49] [Server thread/INFO]: [QuickShop] [OK] End of life Test
[12:38:49] [Server thread/INFO]: [QuickShop] Reading the configuration...
[12:38:49] [Server thread/INFO]: [QuickShop] Developers: PotatoCraft Studio, Netherfoam, Timtower, KaiNoMood (KaiKikuchi), jho5245, Ghost_chu, cakoyo, Ectabro, portlek, log4b0at, Andre601, deadman96385, Vlvxingze, DoctaEnkoda, Mgazul, TiaraRinne, sandtechnology, Starmism, Chris6ix, Rean Schwarzer, mart-r, raphtaliapt, Tim269, creatorfromhell, LoneDev6, judgetread, confuxeon, ibmibmibm, yannicklamprecht, PyvesB, PaulBGD, ORelio, JoschuaSchneider, Starmium, harry0198
[12:38:49] [Server thread/INFO]: [QuickShop] Original author: Netherfoam, Timtower, KaiNoMood
[12:38:49] [Server thread/INFO]: [QuickShop] Let's start loading the plugin
[12:38:49] [Server thread/INFO]: [QuickShop] Chat processor selected: Hardcoded BungeeChat Lib
[12:38:49] [Server thread/INFO]: [QuickShop] Loading plugin translations files...
[12:38:49] [Server thread/INFO]: [QuickShop] Game assets server selected: Mojang API
[12:38:49] [Server thread/INFO]: [QuickShop] Loading items translations...
[12:38:49] [Server thread/INFO]: [QuickShop] Loading enchantments translations...
[12:38:49] [Server thread/INFO]: [QuickShop] Loading potions translations...
[12:38:49] [Server thread/INFO]: [QuickShop] Successfully loaded PlaceHolderAPI support!
[12:38:49] [Server thread/INFO]: [QuickShop] Successfully loaded WorldEdit support!
[12:38:49] [Server thread/INFO]: [QuickShop] Setting up database...
[12:38:49] [Server thread/INFO]: [QuickShop] Checking and updating database columns, it may take a while...
[12:38:49] [Server thread/INFO]: [QuickShop] Finished!
[12:38:49] [Server thread/INFO]: [QuickShop] Selected permission provider: Bukkit
[12:38:49] [Server thread/INFO]: [QuickShop] Registering commands...
[12:38:50] [Server thread/INFO]: [QuickShop] Loaded 1 rules for listener blacklist.
[12:38:50] [Server thread/INFO]: [QuickShop] EventManager selected: QSEventManager
[12:38:50] [Server thread/INFO]: [QuickShop] Fetching shops from the database...If plugin stuck there, check your database connection.
[12:38:50] [Server thread/INFO]: [QuickShop] Loading shops from the database...
[12:38:51] [Server thread/WARN]: [QuickShop] Failed load shop data, because target config can't deserialize the ItemStack
org.bukkit.configuration.InvalidConfigurationException: Exception in deserialize item
	at org.maxgamer.quickshop.util.Util.deserialize(Util.java:368) ~[[快捷商店]QuickShop-5.1.0.4.jar:?]
	at org.maxgamer.quickshop.shop.ShopLoader$ShopDatabaseInfo.deserializeItem(ShopLoader.java:456) ~[[快捷商店]QuickShop-5.1.0.4.jar:?]
	at org.maxgamer.quickshop.shop.ShopLoader$ShopDatabaseInfo.<init>(ShopLoader.java:444) ~[[快捷商店]QuickShop-5.1.0.4.jar:?]
	at org.maxgamer.quickshop.shop.ShopLoader.loadShops(ShopLoader.java:112) ~[[快捷商店]QuickShop-5.1.0.4.jar:?]
	at org.maxgamer.quickshop.shop.ShopLoader.loadShops(ShopLoader.java:81) ~[[快捷商店]QuickShop-5.1.0.4.jar:?]
	at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:960) ~[[快捷商店]QuickShop-5.1.0.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[purpur-1.18.1.jar:git-Purpur-1533]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[purpur-1.18.1.jar:git-Purpur-1533]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:732) ~[purpur-1.18.1.jar:git-Purpur-1533]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:508) ~[purpur-1.18.1.jar:git-Purpur-1533]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:349) ~[purpur-1.18.1.jar:git-Purpur-1533]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[purpur-1.18.1.jar:git-Purpur-1533]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1533]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.yaml.snakeyaml.error.YAMLException: Could not deserialize object
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:50) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[snakeyaml-1.30.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:39) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[snakeyaml-1.30.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:39) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
	at org.bukkit.configuration.file.YamlConstructor.construct(YamlConstructor.java:27) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:158) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:115) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.maxgamer.quickshop.util.Util.deserialize(Util.java:365) ~[[快捷商店]QuickShop-5.1.0.4.jar:?]
	... 16 more
Caused by: java.lang.IllegalArgumentException: Specified class does not exist ('PlayerProfile')
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:197) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:48) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[snakeyaml-1.30.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:39) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[snakeyaml-1.30.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:39) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
	at org.bukkit.configuration.file.YamlConstructor.construct(YamlConstructor.java:27) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:158) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:115) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.maxgamer.quickshop.util.Util.deserialize(Util.java:365) ~[[快捷商店]QuickShop-5.1.0.4.jar:?]
	... 16 more
[12:38:51] [Server thread/WARN]: [QuickShop] ##########FAILED TO LOAD SHOP##########
[12:38:51] [Server thread/WARN]: [QuickShop]   >> Error Info:
[12:38:51] [Server thread/WARN]: [QuickShop] Cannot invoke "org.bukkit.inventory.ItemStack.clone()" because "item" is null
[12:38:51] [Server thread/WARN]: [QuickShop]   >> Error Trace
[12:38:51] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.clone()" because "item" is null
[12:38:51] [Server thread/WARN]: 	at [快捷商店]QuickShop-5.1.0.4.jar//org.maxgamer.quickshop.shop.ContainerShop.<init>(ContainerShop.java:165)
[12:38:51] [Server thread/WARN]: 	at [快捷商店]QuickShop-5.1.0.4.jar//org.maxgamer.quickshop.shop.ShopLoader.loadShops(ShopLoader.java:133)
[12:38:51] [Server thread/WARN]: 	at [快捷商店]QuickShop-5.1.0.4.jar//org.maxgamer.quickshop.shop.ShopLoader.loadShops(ShopLoader.java:81)
[12:38:51] [Server thread/WARN]: 	at [快捷商店]QuickShop-5.1.0.4.jar//org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:960)
[12:38:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[12:38:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[12:38:51] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[12:38:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[12:38:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[12:38:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:732)
[12:38:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:508)
[12:38:51] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:349)
[12:38:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1218)
[12:38:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[12:38:51] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[12:38:51] [Server thread/WARN]: [QuickShop]   >> Target Location Info
[12:38:51] [Server thread/WARN]: [QuickShop] Location: NULL
[12:38:51] [Server thread/WARN]: [QuickShop] Block: NULL
[12:38:51] [Server thread/WARN]: [QuickShop] #######################################
[12:38:51] [Server thread/INFO]: [QuickShop] Registering listeners...
[12:38:51] [Server thread/INFO]: [QuickShop] Cleaning MsgUtils...
[12:38:51] [Server thread/INFO]: [QuickShop] Cleaning purchase messages from the database that are over a week old...
[12:38:51] [Server thread/INFO]: [QuickShop] Log actions is enabled, actions will log in the qs.log file!
[12:38:51] [Server thread/INFO]: [QuickShop] [Shop Purger] Purge not enabled!
[12:38:51] [Server thread/INFO]: [QuickShop] QuickShop Loaded! 2005 ms.
[12:38:51] [Server thread/INFO]: [QuickShop] Using economy system: Essentials Economy
[12:38:51] [Server thread/WARN]: [QuickShop] QuickShop detected tax account not exists, we're trying to create one. If you see any errors, please change tax-account in config.yml to server owner in-game username
[12:38:51] [Server thread/INFO]: [QuickShop] Tax account created.

**Comment by sandtechnology** [comment]
Please update purpur to the latest version and try again, it was caused by outdated server software, in recent commit they introduce playerprofile api.

**Comment by sandtechnology** [comment]
No reply after a long time
