### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Frodwo** [PotatoCraft-Studio/QuickShop-Reremake#141]
### Description

when left click a qs, and type money/amount
Selling shop: player will lose money but will not get item
Buying shop: player will get money but item in shop will not change
OP will not have this situational

### Steps to reproduce

just normally run the server

### Expected Behaviour

.

### Screenshots

![image](https://user-images.githubusercontent.com/70096255/158751757-cfc71585-902f-48b4-95bb-83e4855e17c3.png)

### `/qs paste` URL

https://paste.helpch.at/adofaberuf

**Comment by Frodwo** [comment]
[14:33:21] [Server thread/INFO]: [QuickShop] [DEBUG] [org.maxgamer.quickshop.permission.PermissionManager] [hasPermission] (63) Node: [quickshop.use]; Result: [true]; Sender: [represent_sure]
[14:33:21] [Server thread/INFO]: [QuickShop] [DEBUG] [org.maxgamer.quickshop.shop.RealDisplayItem] [remove] (137) Ignore the Item removing because the Item is already gone or it's a left shop.
[14:33:21] [Server thread/INFO]: [QuickShop] [DEBUG] [org.maxgamer.quickshop.util.ReflectFactory] [getMaterialMinecraftNamespacedKey] (281) Mapping changed during minecraft update, dynamic searching...
[14:33:21] [Server thread/INFO]: [QuickShop] [DEBUG] [org.maxgamer.quickshop.permission.PermissionManager] [hasPermission] (63) Node: [quickshop.preview]; Result: [true]; Sender: [represent_sure]
[14:33:21] [Server thread/INFO]: [QuickShop] [DEBUG] [org.maxgamer.quickshop.util.ReflectFactory] [getMaterialMinecraftNamespacedKey] (281) Mapping changed during minecraft update, dynamic searching...
[14:33:23] [Server thread/INFO]: [QuickShop] [DEBUG] [org.maxgamer.quickshop.permission.PermissionManager] [hasPermission] (63) Node: [quickshop.tax]; Result: [false]; Sender: [represent_sure]
[14:33:23] [Server thread/INFO]: [QuickShop] [DEBUG] [org.maxgamer.quickshop.api.economy.EconomyTransaction] [failSafeCommit] (128) Transaction begin: FailSafe Commit --> 48bd5327-fddd-47c2-9644-14dbfcaca31b => 3f61578b-0fcd-410a-befc-8b5a981a23b9; Amount: 1.0, EconomyCore: BuiltIn-Vault
[14:33:23] [Server thread/INFO]: [QuickShop] [DEBUG] [org.maxgamer.quickshop.api.economy.EconomyTransaction] [commit] (165) Transaction begin: Regular Commit --> 48bd5327-fddd-47c2-9644-14dbfcaca31b => 3f61578b-0fcd-410a-befc-8b5a981a23b9; Amount: 1.0 Total(include tax): 0.95 Tax: 0.05, EconomyCore: BuiltIn-Vault
[14:33:23] [Server thread/WARN]: [QuickShop] Task #106889 for QuickShop v5.1.0.5 generated an exception
java.lang.NullPointerException: Cannot invoke "org.maxgamer.quickshop.util.reporter.error.RollbarErrorReporter.ignoreThrow()" because the return value of "org.maxgamer.quickshop.QuickShop.getSentryErrorReporter()" is null
	at org.maxgamer.quickshop.economy.Economy_Vault.deposit(Economy_Vault.java:152) ~[QuickShop-5.1.0.5.jar:?]
	at org.maxgamer.quickshop.api.economy.EconomyTransaction.commit(EconomyTransaction.java:190) ~[QuickShop-5.1.0.5.jar:?]
	at org.maxgamer.quickshop.api.economy.EconomyTransaction.commit(EconomyTransaction.java:142) ~[QuickShop-5.1.0.5.jar:?]
	at org.maxgamer.quickshop.api.economy.EconomyTransaction.failSafeCommit(EconomyTransaction.java:129) ~[QuickShop-5.1.0.5.jar:?]
	at org.maxgamer.quickshop.shop.SimpleShopManager.actionSell(SimpleShopManager.java:1109) ~[QuickShop-5.1.0.5.jar:?]
	at org.maxgamer.quickshop.shop.SimpleShopManager.actionTrade(SimpleShopManager.java:1476) ~[QuickShop-5.1.0.5.jar:?]
	at org.maxgamer.quickshop.shop.SimpleShopManager.lambda$handleChat$4(SimpleShopManager.java:495) ~[QuickShop-5.1.0.5.jar:?]
	at org.maxgamer.quickshop.shop.SimpleShopManager$$Lambda$11079/0x00000000adc4fe18.run(Unknown Source) ~[QuickShop-5.1.0.5.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-216]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1557) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1273) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer$$Lambda$3940/0x000000004e2a78e8.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Thread.java:884) ~[?:?]

**Comment by sandtechnology** [comment]
How about this version? https://ci.codemc.io/job/PotatoCraft-Studio/job/QuickShop-Reremake-SNAPSHOT/2292/

**Comment by YuanYuanOwO** [comment]
`economy-type: 0` set to `3`

**Comment by Frodwo** [comment]
> `economy-type: 0` set to `3`

thanks
