### ISSUE TITLE
[BUG] exception on paper 1.18

### ISSUE THREAD

**Issue by 4o4E** [PotatoCraft-Studio/QuickShop-Reremake#16]
### Description

run at paper-1.18-47
I'm sorry my English is not good. The following are translated by machine
1. The problem is that when clicking on the store to try to buy, the prompt messages will not be displayed, and the click during purchase cannot be triggered normally; Then the console will report an error
2. The server does not have this problem when it is just started, but after running for a period of time, this problem will occur and an error will be reported on the console
3. The sale will trigger this problem, and the acquisition will not
4. It will be resolved after restart
5. So far, this problem has occurred twice

### Steps to reproduce

Start the server and wait for a while (it may be able to replicate)

### Expected Behaviour

Work normally

### Screenshots

![image](https://user-images.githubusercontent.com/58851040/144812527-928ab72f-88c3-4a72-9a6b-0593626bd2ad.png)

### `/qs paste` URL

https://paste.helpch.at/qilimadisi

### Additional Context

```log
[16:27:19 ERROR]: Could not pass event PlayerInteractEvent to QuickShop v5.0.0.17-SNAPSHOT
java.lang.IllegalArgumentException: java.lang.ClassCastException@673f6bab
        at jdk.internal.reflect.GeneratedMethodAccessor101.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.maxgamer.quickshop.util.ReflectFactory.getMaterialMinecraftNamespacedKey(ReflectFactory.java:281) ~[QuickShop.jar:?]
        at org.maxgamer.quickshop.util.Util.getTranslateComponentForMaterial(Util.java:424) ~[QuickShop.jar:?]
        at org.maxgamer.quickshop.util.MsgUtil.convertItemStackToTranslateText(MsgUtil.java:223) ~[QuickShop.jar:?]
        at org.maxgamer.quickshop.util.MsgUtil.getTranslateText(MsgUtil.java:216) ~[QuickShop.jar:?]
        at org.maxgamer.quickshop.shop.SimpleShopManager.sendShopInfo(SimpleShopManager.java:1217) ~[QuickShop.jar:?]
        at org.maxgamer.quickshop.listener.PlayerListener.postTrade(PlayerListener.java:197) ~[QuickShop.jar:?]
        at org.maxgamer.quickshop.listener.PlayerListener.onClick(PlayerListener.java:90) ~[QuickShop.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor762.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:git-Paper-47]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543) ~[paper-1.18.jar:git-Paper-47]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:506) ~[paper-1.18.jar:git-Paper-47]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:501) ~[paper-1.18.jar:git-Paper-47]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:219) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1744) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.jar:git-Paper-47]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.jar:git-Paper-47]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.jar:git-Paper-47]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.jar:git-Paper-47]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.jar:git-Paper-47]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.jar:git-Paper-47]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.jar:git-Paper-47]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-47]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by sandtechnology** [comment]
How about this version? https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/2035/

**Comment by 4o4E** [comment]
> How about this version? https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/2035/

I'll try. If there are any more questions, I'll reply

**Comment by 4o4E** [comment]
No more problems
