### ISSUE TITLE
[BUG] QuickShop and ItemsAdder Error.

### ISSUE THREAD

**Issue by xfeng36804836** [PotatoCraft-Studio/QuickShop-Reremake#211]
### Description

[23:32:37 ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.UnsupportedOperationException: null
        at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.legacyHoverEventContents(StyleSerializer.java:206) ~[LoneLibs.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:161) ~[LoneLibs.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:49) ~[LoneLibs.jar:?]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1006) ~[gson-2.8.9.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:214) ~[LoneLibs.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:56) ~[LoneLibs.jar:?]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:173) ~[LoneLibs.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:56) ~[LoneLibs.jar:?]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:848) ~[gson-2.8.9.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:87) ~[LoneLibs.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:37) ~[LoneLibs.jar:?]
        at dev.lone.itemsadder.NMS.aE.aE.a(SourceFile:77) ~[ItemsAdder_3.2.3.jar:?]
        at dev.lone.itemsadder.main.jS.f(SourceFile:115) ~[ItemsAdder_3.2.3.jar:?]
        at dev.lone.itemsadder.main.jM.onPacketSending(SourceFile:203) ~[ItemsAdder_3.2.3.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:552) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:94) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:528) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:470) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:436) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:383) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2156) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2142) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:2891) ~[purpur-1.19.jar:git-Purpur-1732]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:2873) ~[purpur-1.19.jar:git-Purpur-1732]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:2853) ~[purpur-1.19.jar:git-Purpur-1732]
        at org.maxgamer.quickshop.chat.platform.minedown.BungeeQuickChat.send(BungeeQuickChat.java:66) ~[QuickShop-5.1.0.9.jar:?]
        at org.maxgamer.quickshop.shop.SimpleShopManager.sendShopInfo(SimpleShopManager.java:1248) ~[QuickShop-5.1.0.9.jar:?]
        at org.maxgamer.quickshop.listener.PlayerListener.postTrade(PlayerListener.java:199) ~[QuickShop-5.1.0.9.jar:?]
        at org.maxgamer.quickshop.listener.PlayerListener.onClick(PlayerListener.java:92) ~[QuickShop-5.1.0.9.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor880.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:git-Purpur-1732]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[purpur-1.19.jar:git-Purpur-1732]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:507) ~[purpur-1.19.jar:git-Purpur-1732]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:199) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1881) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1386) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1363) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1356) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1490) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1209) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:308) ~[purpur-1.19.jar:git-Purpur-1732]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:32:37 ERROR]: Parameters:
  net.minecraft.network.protocol.game.ClientboundSystemChatPacket@2f4c8569[
    content={"extra":[{"color":"dark_purple","hoverEvent":{"action":"show_item","value":[{"text":"{Count:1b,id:\"minecraft:player_head\",tag:{MAGICGEM_NAME:\"随机金币兑换券-1000-100000\",SkullOwner:{Id:[I;-1782210360,1827811680,-1997115688,-266118457],Properties:{textures:[{Value:\"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjM3Y2FlNWM1MWViMTU1OGVhODI4ZjU4ZTBkZmY4ZTZiN2IwYjFhMTgzZDczN2VlY2Y3MTQ2NjE3NjEifX19\"}]}},display:{Lore:[\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\" 使用后按如下概率获得金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\" - 1% 获得 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"100000 \"},{\"italic\":false,\"color\":\"white\",\"text\":\"金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\" - 10% 获得 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"10000 \"},{\"italic\":false,\"color\":\"white\",\"text\":\" 金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\" - 30% 获得 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"2000 \"},{\"italic\":false,\"color\":\"white\",\"text\":\"金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\" - 59% 获得 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"1000 \"},{\"italic\":false,\"color\":\"white\",\"text\":\"金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\"(\"},{\"italic\":false,\"color\":\"red\",\"text\":\"!\"},{\"italic\":false,\"color\":\"gray\",\"text\":\") 右键使用\"}],\"text\":\"\"}\u0027],Name:\u0027{\"extra\":[{\"bold\":true,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":true,\"color\":\"dark_gray\",\"text\":\"||\"},{\"bold\":true,\"italic\":false,\"obfuscated\":false,\"color\":\"yellow\",\"text\":\"随机金币兑换券\"},{\"bold\":true,\"italic\":false,\"obfuscated\":true,\"color\":\"dark_gray\",\"text\":\"||\"}],\"text\":\"\"}\u0027}}}"}]},"text":"| "},{"color":"green","hoverEvent":{"action":"show_item","value":[{"text":"{Count:1b,id:\"minecraft:player_head\",tag:{MAGICGEM_NAME:\"随机金币兑换券-1000-100000\",SkullOwner:{Id:[I;-1782210360,1827811680,-1997115688,-266118457],Properties:{textures:[{Value:\"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjM3Y2FlNWM1MWViMTU1OGVhODI4ZjU4ZTBkZmY4ZTZiN2IwYjFhMTgzZDczN2VlY2Y3MTQ2NjE3NjEifX19\"}]}},display:{Lore:[\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\"使用后按如下概率获得金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\" - 1% 获得 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"100000 \"},{\"italic\":false,\"color\":\"white\",\"text\":\"金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\" - 10% 获得 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"10000 \"},{\"italic\":false,\"color\":\"white\",\"text\":\"金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\" - 30% 获得 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"2000 \"},{\"italic\":false,\"color\":\"white\",\"text\":\"金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\" - 59% 获得 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"1000 \"},{\"italic\":false,\"color\":\"white\",\"text\":\"金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\"(\"},{\"italic\":false,\"color\":\"red\",\"text\":\"!\"},{\"italic\":false,\"color\":\"gray\",\"text\":\") 右键使用\"}],\"text\":\"\"}\u0027],Name:\u0027{\"extra\":[{\"bold\":true,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":true,\"color\":\"dark_gray\",\"text\":\"||\"},{\"bold\":true,\"italic\":false,\"obfuscated\":false,\"color\":\"yellow\",\"text\":\"随机金币兑换券\"},{\"bold\":true,\"italic\":false,\"obfuscated\":true,\"color\":\"dark_gray\",\"text\":\"||\"}],\"text\":\"\"}\u0027}}}"}]},"text":"物品："},{"bold":true,"obfuscated":true,"color":"dark_gray","hoverEvent":{"action":"show_item","value":[{"text":"{Count:1b,id:\"minecraft:player_head\",tag:{MAGICGEM_NAME:\"随机金币兑换券-1000-100000\",SkullOwner:{Id:[I;-1782210360,1827811680,-1997115688,-266118457],Properties:{textures:[{Value:\"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjM3Y2FlNWM1MWViMTU1OGVhODI4ZjU4ZTBkZmY4ZTZiN2IwYjFhMTgzZDczN2VlY2Y3MTQ2NjE3NjEifX19\"}]}},display:{Lore:[\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\"使用后按如下概率获得金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\" - 1% 获得 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"100000 \"},{\"italic\":false,\"color\":\"white\",\"text\":\"金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\" - 10% 获得 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"10000 \"},{\"italic\":false,\"color\":\"white\",\"text\":\"金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\" - 30% 获得 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"2000 \"},{\"italic\":false,\"color\":\"white\",\"text\":\"金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\" - 59% 获得 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"1000 \"},{\"italic\":false,\"color\":\"white\",\"text\":\"金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\"(\"},{\"italic\":false,\"color\":\"red\",\"text\":\"!\"},{\"italic\":false,\"color\":\"gray\",\"text\":\") 右键使用\"}],\"text\":\"\"}\u0027],Name:\u0027{\"extra\":[{\"bold\":true,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":true,\"color\":\"dark_gray\",\"text\":\"||\"},{\"bold\":true,\"italic\":false,\"obfuscated\":false,\"color\":\"yellow\",\"text\":\"随机金币兑换券\"},{\"bold\":true,\"italic\":false,\"obfuscated\":true,\"color\":\"dark_gray\",\"text\":\"||\"}],\"text\":\"\"}\u0027}}}"}]},"text":"||"},{"bold":true,"color":"yellow","hoverEvent":{"action":"show_item","value":[{"text":"{Count:1b,id:\"minecraft:player_head\",tag:{MAGICGEM_NAME:\"随机金币兑换券-1000-100000\",SkullOwner:{Id:[I;-1782210360,1827811680,-1997115688,-266118457],Properties:{textures:[{Value:\"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjM3Y2FlNWM1MWViMTU1OGVhODI4ZjU4ZTBkZmY4ZTZiN2IwYjFhMTgzZDczN2VlY2Y3MTQ2NjE3NjEifX19\"}]}},display:{Lore:[\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\"使用后按如下概率获得金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\" - 1% 获得 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"100000 \"},{\"italic\":false,\"color\":\"white\",\"text\":\"金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\" - 10% 获得 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"10000 \"},{\"italic\":false,\"color\":\"white\",\"text\":\"金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\" - 30% 获得 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"2000 \"},{\"italic\":false,\"color\":\"white\",\"text\":\"金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\" - 59% 获得 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"1000 \"},{\"italic\":false,\"color\":\"white\",\"text\":\"金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\"(\"},{\"italic\":false,\"color\":\"red\",\"text\":\"!\"},{\"italic\":false,\"color\":\"gray\",\"text\":\") 右键使用\"}],\"text\":\"\"}\u0027],Name:\u0027{\"extra\":[{\"bold\":true,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":true,\"color\":\"dark_gray\",\"text\":\"||\"},{\"bold\":true,\"italic\":false,\"obfuscated\":false,\"color\":\"yellow\",\"text\":\"随机金币兑换券\"},{\"bold\":true,\"italic\":false,\"obfuscated\":true,\"color\":\"dark_gray\",\"text\":\"||\"}],\"text\":\"\"}\u0027}}}"}]},"text":"随机金币兑换券"},{"bold":true,"obfuscated":true,"color":"dark_gray","hoverEvent":{"action":"show_item","value":[{"text":"{Count:1b,id:\"minecraft:player_head\",tag:{MAGICGEM_NAME:\"随机金币兑换券-1000-100000\",SkullOwner:{Id:[I;-1782210360,1827811680,-1997115688,-266118457],Properties:{textures:[{Value:\"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjM3Y2FlNWM1MWViMTU1OGVhODI4ZjU4ZTBkZmY4ZTZiN2IwYjFhMTgzZDczN2VlY2Y3MTQ2NjE3NjEifX19\"}]}},display:{Lore:[\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\"使用后按如下概率获得金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\" - 1% 获得 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"100000 \"},{\"italic\":false,\"color\":\"white\",\"text\":\"金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\" - 10% 获得 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"10000 \"},{\"italic\":false,\"color\":\"white\",\"text\":\"金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\" - 30% 获得 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"2000 \"},{\"italic\":false,\"color\":\"white\",\"text\":\"金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\" - 59% 获得 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"1000 \"},{\"italic\":false,\"color\":\"white\",\"text\":\"金币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\"(\"},{\"italic\":false,\"color\":\"red\",\"text\":\"!\"},{\"italic\":false,\"color\":\"gray\",\"text\":\") 右键使用\"}],\"text\":\"\"}\u0027],Name:\u0027{\"extra\":[{\"bold\":true,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":true,\"color\":\"dark_gray\",\"text\":\"||\"},{\"bold\":true,\"italic\":false,\"obfuscated\":false,\"color\":\"yellow\",\"text\":\"随机金币兑换券\"},{\"bold\":true,\"italic\":false,\"obfuscated\":true,\"color\":\"dark_gray\",\"text\":\"||\"}],\"text\":\"\"}\u0027}}}"}]},"text":"||  "},{"bold":true,"obfuscated":true,"color":"dark_gray","text":""},{"text":" "},{"color":"aqua","clickEvent":{"action":"run_command","value":"/qs silentpreview 9a5ff697-2fdd-45d9-93ce-758c308c98cf"},"text":"[物品预览]"}],"text":""}
    b=1
  ]

### Steps to reproduce

Click the store sign and an error will appear

### Expected Behaviour

Reasons for error reporting and Solutions

### Screenshots

no

### `/qs paste` URL

https://paste.helpch.at/nivakuwupu

**Comment by sandtechnology** [comment]
It's lonelibs plugin bug, please report to them, it's not our fault.
