### ISSUE TITLE
[BUG] Could not pass event PlayerArmSwingEvent to QuickShop v5.1.0.9

### ISSUE THREAD

**Issue by xyfwdy** [PotatoCraft-Studio/QuickShop-Reremake#212]
### Description

[21:40:41] [Server thread/ERROR]: Could not pass event PlayerArmSwingEvent to QuickShop v5.1.0.9
java.lang.IllegalStateException: Start block missed in BlockIterator
	at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:171) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:236) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:277) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftLivingEntity.getLineOfSight(CraftLivingEntity.java:179) ~[paper-1.19.1.jar:git-Paper-96]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftLivingEntity.getTargetBlock(CraftLivingEntity.java:201) ~[paper-1.19.1.jar:git-Paper-96]
	at org.maxgamer.quickshop.listener.PlayerListener.onAdventureClick(PlayerListener.java:109) ~[QuickShop-5.1.0.9.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor504.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:git-Paper-96]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleAnimate(ServerGamePacketListenerImpl.java:2736) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:25) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundSwingPacket.a(ServerboundSwingPacket.java:11) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.1.jar:git-Paper-96]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1359) ~[paper-1.19.1.jar:git-Paper-96]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.1.jar:git-Paper-96]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336) ~[paper-1.19.1.jar:git-Paper-96]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[paper-1.19.1.jar:git-Paper-96]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1307) ~[paper-1.19.1.jar:git-Paper-96]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[paper-1.19.1.jar:git-Paper-96]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-96]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Steps to reproduce

check latest.log and found this.

### `/qs paste` URL

http://www.ranmc.cn/paste-6d5908555db442e2b59725d4feec6775.txt

**Comment by sandtechnology** [comment]
Try https://ci.codemc.io/job/PotatoCraft-Studio/job/QuickShop-Reremake-SNAPSHOT/lastSuccessfulBuild/artifact/target/QuickShop-5.1.0.10-SNAPSHOT.jar ?
