### ISSUE TITLE
[BUG] ARM shop bridge

### ISSUE THREAD

**Issue by Bloodlex** [PotatoCraft-Studio/QuickShop-Reremake#24]
### Description

Exception occurs when unselling a region:

```
09.12 20:05:46 [Server] INFO Region dzialka-12 has been unsold! Reason: USER_SELL
09.12 20:05:46 [Server] ERROR Could not pass event RestoreRegionEvent to ArmShopBridge v1.2.5
09.12 20:05:46 [Server] INFO java.lang.IncompatibleClassChangeError: Method 'org.maxgamer.quickshop.api.ShopAPI org.maxgamer.quickshop.api.QuickShopAPI.getShopAPI()' must be InterfaceMethodref constant
09.12 20:05:46 [Server] INFO at net.alex9849.armshopbridge.adapters.QuickShop4Adapter.deleteShops(QuickShop4Adapter.java:35) ~[armshopbridge.jar:?]
09.12 20:05:46 [Server] INFO at net.alex9849.armshopbridge.listener.RestoreRegionListener.handleRegionReset(RestoreRegionListener.java:17) ~[armshopbridge.jar:?]
09.12 20:05:46 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1035.execute(Unknown Source) ~[?:?]
09.12 20:05:46 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1428]
09.12 20:05:46 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1428]
09.12 20:05:46 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1428]
09.12 20:05:46 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-1428]
09.12 20:05:46 [Server] INFO at net.alex9849.arm.regions.Region.restoreRegion(Region.java:936) ~[advancedregionmarket-3.3.5.jar:?]
09.12 20:05:46 [Server] INFO at net.alex9849.arm.regions.Region.automaticResetRegion(Region.java:1081) ~[advancedregionmarket-3.3.5.jar:?]
09.12 20:05:46 [Server] INFO at net.alex9849.arm.regions.Region.userSell(Region.java:1055) ~[advancedregionmarket-3.3.5.jar:?]
09.12 20:05:46 [Server] INFO at net.alex9849.arm.gui.Gui.lambda$openSellWarning$63(Gui.java:783) ~[advancedregionmarket-3.3.5.jar:?]
09.12 20:05:46 [Server] INFO at net.alex9849.arm.gui.Gui.onClick(Gui.java:981) ~[advancedregionmarket-3.3.5.jar:?]
09.12 20:05:46 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor847.execute(Unknown Source) ~[?:?]
09.12 20:05:46 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1428]
09.12 20:05:46 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1428]
09.12 20:05:46 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1428]
09.12 20:05:46 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-1428]
09.12 20:05:46 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2891) ~[app:?]
09.12 20:05:46 [Server] INFO at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:55) ~[app:?]
09.12 20:05:46 [Server] INFO at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:11) ~[app:?]
09.12 20:05:46 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
09.12 20:05:46 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1428]
09.12 20:05:46 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
09.12 20:05:46 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
09.12 20:05:46 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[patched_1.17.1.jar:git-Purpur-1428]
09.12 20:05:46 [Server] INFO at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Purpur-1428]
09.12 20:05:46 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
09.12 20:05:46 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[patched_1.17.1.jar:git-Purpur-1428]
09.12 20:05:46 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1421) ~[patched_1.17.1.jar:git-Purpur-1428]
09.12 20:05:46 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
09.12 20:05:46 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1399) ~[patched_1.17.1.jar:git-Purpur-1428]
09.12 20:05:46 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1310) ~[patched_1.17.1.jar:git-Purpur-1428]
09.12 20:05:46 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
09.12 20:05:46 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
09.12 20:05:47 [Server] INFO Region dzialka-12 has been restored! Reason: USER_SELL
```

### Steps to reproduce

1. Create a region with ARM.
2. Rent a region.
3. Wait for it to expire.
4. Exception occurs.

### Expected Behaviour

No exception

### Screenshots

Not applicable.

### `/qs paste` URL

https://paste.helpch.at/xisupeqiju

**Comment by sandtechnology** [comment]
It's the issue for v5 api, please use advancedregionmarket Integration instead
