### ISSUE TITLE
[BUG] After I create a store, just restart the server and I get this error? why is that?

### ISSUE THREAD

**Issue by Heyh520** [PotatoCraft-Studio/QuickShop-Reremake#410]
### Description

I replaced mysql to store my store information and I found it wasn't the database

### Steps to reproduce

2023-10-19 12:21:29 [04:21:29] [Server thread/WARN] [or.ma.qu.QuickShop/]: [QuickShop] #######################################
2023-10-19 12:21:29 [04:21:29] [Server thread/ERROR] [or.ma.qu.QuickShop/]: [QuickShop] QuickShop detected too many errors when loading shops, you should backup your shop database and ask the developer for help
2023-10-19 12:21:29 [04:21:29] [Server thread/WARN] [or.ma.qu.QuickShop/]: [QuickShop] ##########FAILED TO LOAD SHOP##########
2023-10-19 12:21:29 [04:21:29] [Server thread/WARN] [or.ma.qu.QuickShop/]: [QuickShop]   >> Error Info:
2023-10-19 12:21:29 [04:21:29] [Server thread/WARN] [or.ma.qu.QuickShop/]: [QuickShop] Shop must register into ShopManager before loading.
2023-10-19 12:21:29 [04:21:29] [Server thread/WARN] [or.ma.qu.QuickShop/]: [QuickShop]   >> Error Trace
2023-10-19 12:21:29 [04:21:29] [Server thread/WARN] [/]: java.lang.IllegalStateException: Shop must register into ShopManager before loading.
2023-10-19 12:21:29 [04:21:29] [Server thread/WARN] [/]:        at org.maxgamer.quickshop.shop.ContainerShop.onLoad(ContainerShop.java:1043)
2023-10-19 12:21:29 [04:21:29] [Server thread/WARN] [/]:        at org.maxgamer.quickshop.shop.ShopLoader.lambda$loadShops$0(ShopLoader.java:194)
2023-10-19 12:21:29 [04:21:29] [Server thread/WARN] [/]:        at TRANSFORMER/forge@40.2.10/org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:102)
2023-10-19 12:21:29 [04:21:29] [Server thread/WARN] [/]:        at TRANSFORMER/forge@40.2.10/org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:417)
2023-10-19 12:21:29 [04:21:29] [Server thread/WARN] [/]:        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1205)
2023-10-19 12:21:29 [04:21:29] [Server thread/WARN] [/]:        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:424)
2023-10-19 12:21:29 [04:21:29] [Server thread/WARN] [/]:        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1156)
2023-10-19 12:21:29 [04:21:29] [Server thread/WARN] [/]:        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:954)
2023-10-19 12:21:29 [04:21:29] [Server thread/WARN] [/]:        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:263)
2023-10-19 12:21:29 [04:21:29] [Server thread/WARN] [/]:        at java.base/java.lang.Thread.run(Unknown Source)
2023-10-19 12:21:29 [04:21:29] [Server thread/WARN] [or.ma.qu.QuickShop/]: [QuickShop]   >> Target Location Info
2023-10-19 12:21:29 [04:21:29] [Server thread/WARN] [or.ma.qu.QuickShop/]: [QuickShop] Location: Location{world=CraftWorld{name=world},x=47.0,y=110.0,z=32.0,pitch=0.0,yaw=0.0}
2023-10-19 12:21:29 [04:21:29] [Server thread/WARN] [or.ma.qu.QuickShop/]: [QuickShop] Block: AIR
2023-10-19 12:21:29 [04:21:29] [Server thread/WARN] [or.ma.qu.QuickShop/]: [QuickShop] #######################################
2023-10-19 12:21:29 [04:21:29] [Server thread/ERROR] [or.ma.qu.QuickShop/]: [QuickShop] QuickShop detected too many errors when loading shops, you should backup your shop database and ask the developer for help
2023-10-19 12:21:29 [04:21:29] [Craft Scheduler Thread - 6/INFO] [ne.mi.va.Vault/]: [Vault] Checking for Updates ... 
2023-10-19 12:21:29 [04:21:29] [Craft Scheduler Thread - 19/INFO] [/]: _________________/ Residence \_________________
2023-10-19 12:21:29 [04:21:29] [Craft Scheduler Thread - 19/INFO] [/]: | 5.1.4.0 is now available! Your version: 5.1.3.0
2023-10-19 12:21:29 [04:21:29] [Craft Scheduler Thread - 19/INFO] [/]: ----------------------------------------
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 5/WARN] [or.ma.qu.QuickShop/]: [QuickShop] A exception was thrown, QuickShop already caught this exception and reported it. This error will only shown once before next restart.
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 10/WARN] [or.ma.qu.QuickShop/]: [QuickShop] A exception was thrown, QuickShop already caught this exception and reported it. This error will only shown once before next restart.
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 10/WARN] [or.ma.qu.QuickShop/]: [QuickShop] ====QuickShop Error Report BEGIN===
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 10/WARN] [or.ma.qu.QuickShop/]: [QuickShop] Description: Shop must register into ShopManager before loading.
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 5/WARN] [or.ma.qu.QuickShop/]: [QuickShop] ====QuickShop Error Report BEGIN===
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 5/WARN] [or.ma.qu.QuickShop/]: [QuickShop] Description: Shop must register into ShopManager before loading.
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 10/WARN] [or.ma.qu.QuickShop/]: [QuickShop] Server   ID: aabfa154-de31-4111-8588-dfcf35899821
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 5/WARN] [or.ma.qu.QuickShop/]: [QuickShop] Server   ID: aabfa154-de31-4111-8588-dfcf35899821
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 10/WARN] [or.ma.qu.QuickShop/]: [QuickShop] Exception  : 
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 5/WARN] [or.ma.qu.QuickShop/]: [QuickShop] Exception  : 
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 10/WARN] [/]: java.lang.IllegalStateException: Shop must register into ShopManager before loading.
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 10/WARN] [/]:  at org.maxgamer.quickshop.shop.ContainerShop.onLoad(ContainerShop.java:1043)
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 10/WARN] [/]:  at org.maxgamer.quickshop.listener.ChunkListener.lambda$onChunkLoad$0(ChunkListener.java:52)
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 10/WARN] [/]:  at TRANSFORMER/forge@40.2.10/org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:102)
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 10/WARN] [/]:  at TRANSFORMER/forge@40.2.10/org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:417)
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 10/WARN] [/]:  at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1205)
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 10/WARN] [/]:  at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:424)
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 10/WARN] [/]:  at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1156)
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 10/WARN] [/]:  at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:954)
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 10/WARN] [/]:  at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:263)
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 10/WARN] [/]:  at java.base/java.lang.Thread.run(Unknown Source)
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 5/WARN] [/]: java.lang.IllegalStateException: Shop must register into ShopManager before loading.
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 5/WARN] [/]:   at org.maxgamer.quickshop.shop.ContainerShop.onLoad(ContainerShop.java:1043)
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 5/WARN] [/]:   at org.maxgamer.quickshop.listener.ChunkListener.lambda$onChunkLoad$0(ChunkListener.java:52)
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 5/WARN] [/]:   at TRANSFORMER/forge@40.2.10/org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:102)
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 5/WARN] [/]:   at TRANSFORMER/forge@40.2.10/org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:417)
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 10/WARN] [or.ma.qu.QuickShop/]: [QuickShop] ====QuickShop Error Report E N D===
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 5/WARN] [/]:   at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1205)
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 5/WARN] [/]:   at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:424)
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 5/WARN] [/]:   at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1156)
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 5/WARN] [/]:   at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:954)
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 5/WARN] [/]:   at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:263)
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 5/WARN] [/]:   at java.base/java.lang.Thread.run(Unknown Source)
2023-10-19 12:21:35 [04:21:35] [Craft Scheduler Thread - 5/WARN] [or.ma.qu.QuickShop/]: [QuickShop] ====QuickShop Error Report E N D===

### Expected Behaviour

I have changed 5.1.2.2 same question, what is this shopmapper?

### Screenshots

![微信图片编辑_20231019122908](https://github.com/PotatoCraft-Studio/QuickShop-Reremake/assets/94290561/f736ff3b-66b6-46f1-a643-4f4c43e28aea)

### `/qs paste` URL

https://paste.helpch.at/iwusuwunax

**Comment by YuanYuanOwO** [comment]
HyBird (Forge/Fabric+Spigot) Server Software is not support by QuickShop
