### ISSUE TITLE
[request] Adaptation 1.20.4

### ISSUE THREAD

**Issue by CatTeaA** [PotatoCraft-Studio/QuickShop-Reremake#432]
### Description

Adaptation 1.20.4
The console displays that this version is not supported

### Steps to reproduce

Adaptation 1.20.4
The console displays that this version is not supported

### Expected Behaviour

Normal operation

### Screenshots

[06:53:43 WARN]: [QuickShop] [WARN] CoreSupport Test: QuickShop may not fully support version v1_20_R3/1.20.4, Some features may not work.
[06:53:43 ERROR]: [QuickShop] Virtual DisplayItem Support Test: Failed to initialize VirtualDisplayItem
java.lang.IllegalStateException: This game version UNKNOWN not supports Virtual DisplayItem.
        at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.virtualDisplaySupportTest(EnvironmentChecker.java:425) ~[QuickShop-5.1.2.5.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.run(EnvironmentChecker.java:123) ~[QuickShop-5.1.2.5.jar:?]
        at org.maxgamer.quickshop.QuickShop.runtimeCheck(QuickShop.java:869) ~[QuickShop-5.1.2.5.jar:?]
        at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:961) ~[QuickShop-5.1.2.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[purpur-1.20.4.jar:git-Purpur-2113]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2113]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:651) ~[purpur-1.20.4.jar:git-Purpur-2113]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:562) ~[purpur-1.20.4.jar:git-Purpur-2113]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[purpur-1.20.4.jar:git-Purpur-2113]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.20.4.jar:git-Purpur-2113]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.4.jar:git-Purpur-2113]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1148) ~[purpur-1.20.4.jar:git-Purpur-2113]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2113]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[06:53:43 WARN]: [QuickShop] [WARN] Virtual DisplayItem Support Test: Virtual DisplayItem seems to not work on this Minecraft server, Make sure QuickShop, ProtocolLib and server builds are up to date.
[06:53:43 WARN]: [QuickShop] [WARN] GameVersion supporting Test: Your Minecraft server version not tested by developers, QuickShop may ran into issues on this version.

### `/qs paste` URL

null

**Comment by CCjun6** [comment]
I'm also waiting for the author of 1.20.4 to update when he is free.

**Comment by JuergenUniVie** [comment]
same:

[07:57:19 WARN]: [QuickShop] [WARN] CoreSupport Test: QuickShop may not fully support version v1_20_R3/1.20.4, Some features may not work.
[07:57:19 ERROR]: [QuickShop] Virtual DisplayItem Support Test: Failed to initialize VirtualDisplayItem
java.lang.IllegalStateException: This game version UNKNOWN not supports Virtual DisplayItem.
        at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.virtualDisplaySupportTest(EnvironmentChecker.java:425) ~[QuickShop-5.1.2.5.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.run(EnvironmentChecker.java:123) ~[QuickShop-5.1.2.5.jar:?]
        at org.maxgamer.quickshop.QuickShop.runtimeCheck(QuickShop.java:869) ~[QuickShop-5.1.2.5.jar:?]
        at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:961) ~[QuickShop-5.1.2.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.4.jar:git-Paper-377]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-377]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:git-Paper-377]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:git-Paper-377]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:673) ~[paper-1.20.4.jar:git-Paper-377]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.20.4.jar:git-Paper-377]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.4.jar:git-Paper-377]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-377]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-377]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
[07:57:19 WARN]: [QuickShop] [WARN] Virtual DisplayItem Support Test: Virtual DisplayItem seems to not work on this Minecraft server, Make sure QuickShop, ProtocolLib and server builds are up to date.
[07:57:19 WARN]: [QuickShop] [WARN] GameVersion supporting Test: Your Minecraft server version not tested by developers, QuickShop may ran into issues on this version.

**Comment by 4b75726169736859** [comment]
hi, try this https://modrinth.com/plugin/quickshop-hikari

**Comment by 4b75726169736859** [comment]
> same:
> 
> [07:57:19 WARN]: [QuickShop] [WARN] CoreSupport Test: QuickShop may not fully support version v1_20_R3/1.20.4, Some features may not work. [07:57:19 ERROR]: [QuickShop] Virtual DisplayItem Support Test: Failed to initialize VirtualDisplayItem java.lang.IllegalStateException: This game version UNKNOWN not supports Virtual DisplayItem. at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.virtualDisplaySupportTest(EnvironmentChecker.java:425) ~[QuickShop-5.1.2.5.jar:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.run(EnvironmentChecker.java:123) ~[QuickShop-5.1.2.5.jar:?] at org.maxgamer.quickshop.QuickShop.runtimeCheck(QuickShop.java:869) ~[QuickShop-5.1.2.5.jar:?] at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:961) ~[QuickShop-5.1.2.5.jar:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.4.jar:git-Paper-377] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-377] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:git-Paper-377] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:git-Paper-377] at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:673) ~[paper-1.20.4.jar:git-Paper-377] at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.20.4.jar:git-Paper-377] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.4.jar:git-Paper-377] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-377] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-377] at java.lang.Thread.run(Unknown Source) ~[?:?] [07:57:19 WARN]: [QuickShop] [WARN] Virtual DisplayItem Support Test: Virtual DisplayItem seems to not work on this Minecraft server, Make sure QuickShop, ProtocolLib and server builds are up to date. [07:57:19 WARN]: [QuickShop] [WARN] GameVersion supporting Test: Your Minecraft server version not tested by developers, QuickShop may ran into issues on this version.

Hi, try this plugin https://modrinth.com/plugin/quickshop-hikari
that solved the problem for me.

I followed the recommendations in the PotatoCraft Studio discord server announcement channel
![2024-01-10T15 22 19,322078605+01 00](https://github.com/PotatoCraft-Studio/QuickShop-Reremake/assets/32509744/89c3d36a-e9f2-4827-ba39-48e7456f8d9d)

**Comment by 4b75726169736859** [comment]
> > same:
> > [07:57:19 WARN]: [QuickShop] [WARN] CoreSupport Test: QuickShop may not fully support version v1_20_R3/1.20.4, Some features may not work. [07:57:19 ERROR]: [QuickShop] Virtual DisplayItem Support Test: Failed to initialize VirtualDisplayItem java.lang.IllegalStateException: This game version UNKNOWN not supports Virtual DisplayItem. at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.virtualDisplaySupportTest(EnvironmentChecker.java:425) ~[QuickShop-5.1.2.5.jar:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.run(EnvironmentChecker.java:123) ~[QuickShop-5.1.2.5.jar:?] at org.maxgamer.quickshop.QuickShop.runtimeCheck(QuickShop.java:869) ~[QuickShop-5.1.2.5.jar:?] at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:961) ~[QuickShop-5.1.2.5.jar:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.4.jar:git-Paper-377] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-377] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:git-Paper-377] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:git-Paper-377] at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:673) ~[paper-1.20.4.jar:git-Paper-377] at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.20.4.jar:git-Paper-377] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.4.jar:git-Paper-377] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-377] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-377] at java.lang.Thread.run(Unknown Source) ~[?:?] [07:57:19 WARN]: [QuickShop] [WARN] Virtual DisplayItem Support Test: Virtual DisplayItem seems to not work on this Minecraft server, Make sure QuickShop, ProtocolLib and server builds are up to date. [07:57:19 WARN]: [QuickShop] [WARN] GameVersion supporting Test: Your Minecraft server version not tested by developers, QuickShop may ran into issues on this version.
> 
> Hi, try this plugin https://modrinth.com/plugin/quickshop-hikari that solved the problem for me.
> 
> I followed the recommendations in the PotatoCraft Studio discord server announcement channel ![2024-01-10T15 22 19,322078605+01 00](https://private-user-images.githubusercontent.com/32509744/295597458-89c3d36a-e9f2-4827-ba39-48e7456f8d9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4OTcwMTYsIm5iZiI6MTcwNDg5NjcxNiwicGF0aCI6Ii8zMjUwOTc0NC8yOTU1OTc0NTgtODljM2QzNmEtZTlmMi00ODI3LWJhMzktNDhlNzQ1NmY4ZDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDE0MjUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNTM1YzcyZjJkMjNiMDQyOTcxYTk2YjljMGRmNjYzZjkyMTM2Njc3MjgxZTIwMjAzMjI3ODM4OWE5NmUxMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0dAAC_JMk1gYcEs7jKrXS4haRgiVQryCPPDl_eIvr3g)

@BangXi Didn't it work for you?
Explain

**Comment by CatTeaA** [comment]
> > > same:
> > > [07:57:19 WARN]: [QuickShop] [WARN] CoreSupport Test: QuickShop may not fully support version v1_20_R3/1.20.4, Some features may not work. [07:57:19 ERROR]: [QuickShop] Virtual DisplayItem Support Test: Failed to initialize VirtualDisplayItem java.lang.IllegalStateException: This game version UNKNOWN not supports Virtual DisplayItem. at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.virtualDisplaySupportTest(EnvironmentChecker.java:425) ~[QuickShop-5.1.2.5.jar:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.run(EnvironmentChecker.java:123) ~[QuickShop-5.1.2.5.jar:?] at org.maxgamer.quickshop.QuickShop.runtimeCheck(QuickShop.java:869) ~[QuickShop-5.1.2.5.jar:?] at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:961) ~[QuickShop-5.1.2.5.jar:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.4.jar:git-Paper-377] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-377] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:git-Paper-377] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:git-Paper-377] at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:673) ~[paper-1.20.4.jar:git-Paper-377] at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.20.4.jar:git-Paper-377] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.4.jar:git-Paper-377] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-377] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-377] at java.lang.Thread.run(Unknown Source) ~[?:?] [07:57:19 WARN]: [QuickShop] [WARN] Virtual DisplayItem Support Test: Virtual DisplayItem seems to not work on this Minecraft server, Make sure QuickShop, ProtocolLib and server builds are up to date. [07:57:19 WARN]: [QuickShop] [WARN] GameVersion supporting Test: Your Minecraft server version not tested by developers, QuickShop may ran into issues on this version.
> > 
> > 
> > Hi, try this plugin https://modrinth.com/plugin/quickshop-hikari that solved the problem for me.
> > I followed the recommendations in the PotatoCraft Studio discord server announcement channel ![2024-01-10T15 22 19,322078605+01 00](https://private-user-images.githubusercontent.com/32509744/295597458-89c3d36a-e9f2-4827-ba39-48e7456f8d9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4OTcwMTYsIm5iZiI6MTcwNDg5NjcxNiwicGF0aCI6Ii8zMjUwOTc0NC8yOTU1OTc0NTgtODljM2QzNmEtZTlmMi00ODI3LWJhMzktNDhlNzQ1NmY4ZDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDE0MjUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNTM1YzcyZjJkMjNiMDQyOTcxYTk2YjljMGRmNjYzZjkyMTM2Njc3MjgxZTIwMjAzMjI3ODM4OWE5NmUxMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0dAAC_JMk1gYcEs7jKrXS4haRgiVQryCPPDl_eIvr3g)
> 
> @BangXi Didn't it work for you? Explain

I didn't know about it before.
In fact, you've helped me, I've migrated
Thank you❤️

**Comment by 4b75726169736859** [comment]
No problem ;)

**Comment by postyizhan** [comment]
I'm also waiting for the author of 1.20.4 to update when he is free.
