### ISSUE TITLE
[BUG] An error occurred when Quickshop checked for translated text updates, causing lengthy server startup wait times

### ISSUE THREAD

**Issue by DICEALPHAHU** [PotatoCraft-Studio/QuickShop-Reremake#439]
### Description

An error occurred when Quickshop checked for translated text updates, causing lengthy server startup wait times
Quickshop检查翻译文本更新时出现错误，导致服务器启动等待时间变得很长

### Steps to reproduce

1.use Quickshop reremake 5.1.2.5
2.start server
3.show error

### Expected Behaviour

Please set a configuration that server administrators decide for themselves whether they need to update the translated text, due to the peculiarities of the network, I may not be the only one with this problem
麻烦弄一个选项，服务器管理人员自行决定是否需要更新翻译文本，由于网络的特殊性(GFW)，可能不止我一个人有这个问题

### Screenshots

![QQ截图20240104035530](https://github.com/PotatoCraft-Studio/QuickShop-Reremake/assets/98395726/725e5702-c2ea-4e1d-b2fd-4b1b83351b50)
[03:47:22 INFO]: [QuickShop] Loading server plugin QuickShop v5.1.2.5
[03:47:22 INFO]: [QuickShop] QuickShop Reremake - Early boot step - Booting up
[03:47:22 INFO]: [QuickShop] [OK] Signature Verify
[03:47:22 INFO]: [QuickShop] [OK] Plugin Manifest Check
[03:47:22 INFO]: [QuickShop] [OK] Potential Infection Characteristics Check
[03:47:22 INFO]: [QuickShop] Reading the configuration...
[03:47:22 INFO]: [QuickShop] Loading messages translation over-the-air (this may need take a while).
[03:47:22 INFO]: [QuickShop] Translation over-the-air platform selected: Crowdin
[03:47:22 INFO]: [QuickShop] Checking for translation updates, this may need a while...
[03:47:30 ERROR]: Failed to request yggdrasil public key
com.mojang.authlib.exceptions.AuthenticationUnavailableException: Cannot contact authentication server
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:119) ~[authlib-4.0.43.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:91) ~[authlib-4.0.43.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo.fetch(YggdrasilServicesKeyInfo.java:94) ~[authlib-4.0.43.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo.lambda$get$1(YggdrasilServicesKeyInfo.java:81) ~[authlib-4.0.43.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.net.SocketTimeoutException: Connect timed out
        at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:543) ~[?:?]
        at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:594) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
        at java.net.Socket.connect(Socket.java:633) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299) ~[?:?]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:178) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:498) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:603) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:378) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1287) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
        at com.mojang.authlib.HttpAuthenticationService.performGetRequest(HttpAuthenticationService.java:140) ~[authlib-4.0.43.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:96) ~[authlib-4.0.43.jar:?]
        ... 9 more
[03:51:02 INFO]: [QuickShop] Loading up integration modules.
[03:51:02 INFO]: [QuickShop] QuickShop Reremake - Early boot step - Complete

### `/qs paste` URL

it's in Additional Context

### Additional Context

[paste-438413343dc9469aa3d2742e43193d4c.txt](https://github.com/PotatoCraft-Studio/QuickShop-Reremake/files/13822844/paste-438413343dc9469aa3d2742e43193d4c.txt)
pastebin上传不了云端，这个是pastebin文件

**Comment by sandtechnology** [comment]
Look like it take about 3mins+ to load (skip this checking), will investigate that, thanks for reporting!
