### ISSUE TITLE
[BUG] Selling items that have "reset" color

### ISSUE THREAD

**Issue by dtzdev** [PotatoCraft-Studio/QuickShop-Reremake#440]
### Description

MC Version: 1.20.4

When you are selling items that have been made to have reset in coloring quickshop throws this error:

[22:57:23 ERROR]: Could not pass event PlayerInteractEvent to QuickShop v5.1.2.5
com.google.gson.JsonParseException: Invalid color name: reset; Invalid color name: reset; Invalid color name: reset
        at net.minecraft.Util.getOrThrow(Util.java:882) ~[?:?]
        at net.minecraft.network.chat.Component$Serializer.deserialize(Component.java:291) ~[?:?]
        at net.minecraft.network.chat.Component$Serializer.fromJson(Component.java:310) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.<init>(ClientboundSystemChatPacket.java:12) ~[purpur-1.20.4.jar:git-Purpur-2118]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3329) ~[purpur-1.20.4.jar:git-Purpur-2118]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3317) ~[purpur-1.20.4.jar:git-Purpur-2118]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3297) ~[purpur-1.20.4.jar:git-Purpur-2118]
        at org.maxgamer.quickshop.chat.platform.minedown.BungeeQuickChat.send(BungeeQuickChat.java:101) ~[QuickShop-5.1.2.5.jar:?]
        at org.maxgamer.quickshop.shop.SimpleShopManager.sendShopInfo(SimpleShopManager.java:1273) ~[QuickShop-5.1.2.5.jar:?]
        at org.maxgamer.quickshop.listener.PlayerListener.postTrade(PlayerListener.java:239) ~[QuickShop-5.1.2.5.jar:?]
        at org.maxgamer.quickshop.listener.PlayerListener.onClick(PlayerListener.java:106) ~[QuickShop-5.1.2.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor317.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2118]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2118]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2118]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:592) ~[purpur-1.20.4.jar:git-Purpur-2118]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549) ~[purpur-1.20.4.jar:git-Purpur-2118]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543) ~[purpur-1.20.4.jar:git-Purpur-2118]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:199) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1921) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2118]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1485) ~[purpur-1.20.4.jar:git-Purpur-2118]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2118]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1462) ~[purpur-1.20.4.jar:git-Purpur-2118]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1385) ~[purpur-1.20.4.jar:git-Purpur-2118]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1363) ~[purpur-1.20.4.jar:git-Purpur-2118]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.20.4.jar:git-Purpur-2118]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2118]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

### Steps to reproduce

1. Create item in [gamergeek.net give generator](https://www.gamergeeks.net/apps/minecraft/give-command-generator) that has at some point reset color.
2. Sell that item and it throws the error.

### Expected Behaviour

Quickshop would handle the item. 

### Screenshots

null

### `/qs paste` URL

null

**Comment by sandtechnology** [comment]
it's likely is the upstream (spigot/paper) issue, could you reproduce this in spigot?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: dtz ***@***.***>
Sent: Monday, January 8, 2024 5:09:46 AM
To: PotatoCraft-Studio/QuickShop-Reremake ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PotatoCraft-Studio/QuickShop-Reremake] [BUG] Selling items that have "reset" color (Issue #440)


Description

MC Version: 1.20.4

When you are selling items that have been made to have reset in coloring quickshop throws this error:

[22:57:23 ERROR]: Could not pass event PlayerInteractEvent to QuickShop v5.1.2.5
com.google.gson.JsonParseException: Invalid color name: reset; Invalid color name: reset; Invalid color name: reset
at net.minecraft.Util.getOrThrow(Util.java:882) ~[?:?]
at net.minecraft.network.chat.Component$Serializer.deserialize(Component.java:291) ~[?:?]
at net.minecraft.network.chat.Component$Serializer.fromJson(Component.java:310) ~[?:?]
at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.(ClientboundSystemChatPacket.java:12) ~[purpur-1.20.4.jar:git-Purpur-2118]
at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3329) ~[purpur-1.20.4.jar:git-Purpur-2118]
at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3317) ~[purpur-1.20.4.jar:git-Purpur-2118]
at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3297) ~[purpur-1.20.4.jar:git-Purpur-2118]
at org.maxgamer.quickshop.chat.platform.minedown.BungeeQuickChat.send(BungeeQuickChat.java:101) ~[QuickShop-5.1.2.5.jar:?]
at org.maxgamer.quickshop.shop.SimpleShopManager.sendShopInfo(SimpleShopManager.java:1273) ~[QuickShop-5.1.2.5.jar:?]
at org.maxgamer.quickshop.listener.PlayerListener.postTrade(PlayerListener.java:239) ~[QuickShop-5.1.2.5.jar:?]
at org.maxgamer.quickshop.listener.PlayerListener.onClick(PlayerListener.java:106) ~[QuickShop-5.1.2.5.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor317.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2118]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2118]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2118]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:592) ~[purpur-1.20.4.jar:git-Purpur-2118]
at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549) ~[purpur-1.20.4.jar:git-Purpur-2118]
at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543) ~[purpur-1.20.4.jar:git-Purpur-2118]
at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:199) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1921) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2118]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1485) ~[purpur-1.20.4.jar:git-Purpur-2118]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2118]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1462) ~[purpur-1.20.4.jar:git-Purpur-2118]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1385) ~[purpur-1.20.4.jar:git-Purpur-2118]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1363) ~[purpur-1.20.4.jar:git-Purpur-2118]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.20.4.jar:git-Purpur-2118]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2118]
at java.lang.Thread.run(Thread.java:840) ~[?:?]

Steps to reproduce

  1.  Create item in gamergeek.net give generator<https://www.gamergeeks.net/apps/minecraft/give-command-generator> that has at some point reset color.
  2.  Sell that item and it throws the error.

Expected Behaviour

Quickshop would handle the item.

Screenshots

null

/qs paste URL

null

Additional Context

No response

**Comment by dtzdev** [comment]
Latest paper reproduces the error
I will test spigot in a moment
