### ISSUE TITLE
[BUG] Could not pass event ShopModeratorChangedEvent to QuickShop v5.1.0.2

### ISSUE THREAD

**Issue by Happy-Hop7** [PotatoCraft-Studio/QuickShop-Reremake#46]
### Description

Changing a Shop to an unlimited admin shop throws an exception.

### Steps to reproduce

1. Use this config options:
```
#Turn on this option will migrate shop owner to specified account when you set a shop to unlimited.
#It won't affect exists shops, you will need switch to unlimited again to apply it.
unlimited-shop-owner-change: true

#This account will used for unlimited shop if you have turned on unlimited-shop-owner-change.
unlimited-shop-owner-change-account: AdminShop

```
2. Create a Shop
3. Change to unlimited

### Expected Behaviour

No Exception

### Screenshots

-

### `/qs paste` URL

https://paste.helpch.at/daxuduyayu

### Additional Context
```
[11:19:52 ERROR]: Could not pass event ShopModeratorChangedEvent to QuickShop v5.1.0.2
java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.String java.util.TimeZone.ID accessible: module java.base does not "opens java.util" to unnamed module @f8c1ddd
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.lang.reflect.Field.checkCanSetAccessible(Field.java:178) ~[?:?]
        at java.lang.reflect.Field.setAccessible(Field.java:172) ~[?:?]
        at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.Gson.getAdapter(Gson.java:458) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.Gson.getAdapter(Gson.java:458) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.Gson.getAdapter(Gson.java:458) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.Gson.getAdapter(Gson.java:458) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:56) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.Gson.toJson(Gson.java:704) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.Gson.toJson(Gson.java:683) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.Gson.toJson(Gson.java:638) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.Gson.toJson(Gson.java:618) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at org.maxgamer.quickshop.QuickShop.logEvent(QuickShop.java:449) ~[QuickShop-5.1.0.2.jar:?]
        at org.maxgamer.quickshop.listener.InternalListener.shopModeratorChanges(InternalListener.java:87) ~[QuickShop-5.1.0.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor498.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at org.maxgamer.quickshop.shop.ContainerShop.setOwner(ContainerShop.java:1029) ~[QuickShop-5.1.0.2.jar:?]
        at org.maxgamer.quickshop.shop.SimpleShopManager.migrateOwnerToUnlimitedShopOwner(SimpleShopManager.java:1491) ~[QuickShop-5.1.0.2.jar:?]
        at org.maxgamer.quickshop.command.subcommand.SubCommand_Unlimited.onCommand(SubCommand_Unlimited.java:52) ~[QuickShop-5.1.0.2.jar:?]
        at org.maxgamer.quickshop.command.subcommand.SubCommand_Unlimited.onCommand(SubCommand_Unlimited.java:32) ~[QuickShop-5.1.0.2.jar:?]
        at org.maxgamer.quickshop.command.SimpleCommandManager.onCommand(SimpleCommandManager.java:430) ~[QuickShop-5.1.0.2.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2344) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2155) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2136) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1421) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1560) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1300) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[11:19:52 ERROR]: Could not pass event ShopModeratorChangedEvent to QuickShop v5.1.0.2
java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.String java.util.TimeZone.ID accessible: module java.base does not "opens java.util" to unnamed module @f8c1ddd
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.lang.reflect.Field.checkCanSetAccessible(Field.java:178) ~[?:?]
        at java.lang.reflect.Field.setAccessible(Field.java:172) ~[?:?]
        at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.Gson.getAdapter(Gson.java:458) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.Gson.getAdapter(Gson.java:458) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.Gson.getAdapter(Gson.java:458) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.Gson.getAdapter(Gson.java:458) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:56) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.Gson.toJson(Gson.java:704) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.Gson.toJson(Gson.java:683) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.Gson.toJson(Gson.java:638) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at com.google.gson.Gson.toJson(Gson.java:618) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at org.maxgamer.quickshop.QuickShop.logEvent(QuickShop.java:449) ~[QuickShop-5.1.0.2.jar:?]
        at org.maxgamer.quickshop.listener.InternalListener.shopModeratorChanges(InternalListener.java:87) ~[QuickShop-5.1.0.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor498.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at org.maxgamer.quickshop.shop.ContainerShop.setOwner(ContainerShop.java:1029) ~[QuickShop-5.1.0.2.jar:?]
        at org.maxgamer.quickshop.shop.SimpleShopManager.migrateOwnerToUnlimitedShopOwner(SimpleShopManager.java:1491) ~[QuickShop-5.1.0.2.jar:?]
        at org.maxgamer.quickshop.command.subcommand.SubCommand_Unlimited.onCommand(SubCommand_Unlimited.java:52) ~[QuickShop-5.1.0.2.jar:?]
        at org.maxgamer.quickshop.command.subcommand.SubCommand_Unlimited.onCommand(SubCommand_Unlimited.java:32) ~[QuickShop-5.1.0.2.jar:?]
        at org.maxgamer.quickshop.command.SimpleCommandManager.onCommand(SimpleCommandManager.java:430) ~[QuickShop-5.1.0.2.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2344) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2155) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2136) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1421) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1560) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1300) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
_No response_
```

**Comment by sandtechnology** [comment]
Fixed in the latest snapshot: https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/
