### ISSUE TITLE
[BUG] Report an error when running on 1.20.4

### ISSUE THREAD

**Issue by yyhhkya** [PotatoCraft-Studio/QuickShop-Reremake#477]
### Description

[18:14:53] [Server thread/WARN]: [QuickShop] [WARN] CoreSupport Test: QuickShop may not fully support version v1_20_R3/1.20.4, Some features may not work.
[18:14:53] [Server thread/ERROR]: [QuickShop] Virtual DisplayItem Support Test: Failed to initialize VirtualDisplayItem
java.lang.IllegalStateException: This game version UNKNOWN not supports Virtual DisplayItem.
	at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.virtualDisplaySupportTest(EnvironmentChecker.java:425) ~[[Q][箱子商店]QuickShop-5.1.2.5.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.run(EnvironmentChecker.java:123) ~[[Q][箱子商店]QuickShop-5.1.2.5.jar:?]
	at org.maxgamer.quickshop.QuickShop.runtimeCheck(QuickShop.java:869) ~[[Q][箱子商店]QuickShop-5.1.2.5.jar:?]
	at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:961) ~[[Q][箱子商店]QuickShop-5.1.2.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[18:14:53] [Server thread/WARN]: [QuickShop] [WARN] Virtual DisplayItem Support Test: Virtual DisplayItem seems to not work on this Minecraft server, Make sure QuickShop, ProtocolLib and server builds are up to date.
[18:14:53] [Server thread/WARN]: [QuickShop] [WARN] GameVersion supporting Test: Your Minecraft server version not tested by developers, QuickShop may ran into issues on this version.

### Steps to reproduce

1

### Expected Behaviour

1

### Screenshots

1

### `/qs paste` URL

https://paste.helpch.at/emareniwah

**Comment by YuanYuanOwO** [comment]
已知问题，如果你只是运行1.20.4的服务器，可以使用这个fork https://github.com/tianji-server/QuickShop-Reremake
