### ISSUE TITLE
[BUG] An error occurred while stopping the server

### ISSUE THREAD

**Issue by AdminHcat** [PotatoCraft-Studio/QuickShop-Reremake#95]
### Description

An error occurred while stopping the server，Failed to shut down the server，This keeps my server stuck when it automatically restarts

### Steps to reproduce

stop server

### Expected Behaviour

stop server

### Screenshots

-

### `/qs paste` URL

-

### Additional Context

$[07:08:55 INFO]: Stopping the server
[07:08:56 INFO]: Stopping server
[07:08:56 INFO]: [PlugManX] Disabling PlugManX v2.2.8
[07:08:56 INFO]: [DiceFurniture] Disabling DiceFurniture v3.6.0
[07:08:56 INFO]: [FurnitureLib] Disabling FurnitureLib v2.6
[07:08:56 INFO]: [FurnitureLib] ==========================================
[07:08:56 INFO]: [FurnitureLib] Furniture shutdown started
[07:08:56 INFO]: [de.Ste3et_C0st.FurnitureLib.Database.com.zaxxer.hikari.HikariDataSource] FurnitureLib - Starting...
[07:08:56 INFO]: [de.Ste3et_C0st.FurnitureLib.Database.com.zaxxer.hikari.HikariDataSource] FurnitureLib - Start completed.
[07:08:56 INFO]: [FurnitureLib] FurnitureLib Started SQLite database. Took 2ms
[07:08:56 INFO]: [FurnitureLib] Furniture save started
[07:08:56 INFO]: [FurnitureLib] the list of objects is empty.
[07:08:56 INFO]: [FurnitureLib] ==========================================
[07:08:56 INFO]: [BetterRTP] Disabling BetterRTP v3.2.1-4
[07:08:56 INFO]: [ProtectionLib] Disabling ProtectionLib v1.4
[07:08:56 INFO]: [QuickShop] Disabling QuickShop v5.1.0.4-SNAPSHOT
[07:08:56 INFO]: [QuickShop] QuickShop is finishing remaining work, this may need a while...
[07:08:56 WARN]: java.lang.ClassNotFoundException: org.bukkit.bukkit.Bukkit
[07:08:56 WARN]:        at java.base/java.lang.Class.forNameImpl(Native Method)
[07:08:56 WARN]:        at java.base/java.lang.Class.forName(Class.java:356)
[07:08:56 WARN]:        at QuickShop-5.1.0.4-SNAPSHOT.jar//org.maxgamer.quickshop.nonquickshopstuff.net.ess3.essentialsx.PaperServerStateProvider.isStopping(PaperServerStateProvider.java:11)
[07:08:56 WARN]:        at QuickShop-5.1.0.4-SNAPSHOT.jar//org.maxgamer.quickshop.QuickShop.onDisable(QuickShop.java:646)
[07:08:56 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[07:08:56 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401)
[07:08:56 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537)
[07:08:56 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:514)
[07:08:56 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.disablePlugins(CraftServer.java:498)
[07:08:56 WARN]:        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:1049)
[07:08:56 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.t(DedicatedServer.java:839)
[07:08:56 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1342)
[07:08:56 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[07:08:56 WARN]:        at net.minecraft.server.MinecraftServer$$Lambda$3973/0x0000000064039450.run(Unknown Source)
[07:08:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:884)
[07:08:56 WARN]: [QuickShop] QuickShop has been unloaded while server running, please note that this may cause unexpected behavior.
[07:08:56 WARN]: [QuickShop] If you need reload QuickShop configuration, use /qs reload command instead.
2022-02-08 07:08:56,075 Server thread ERROR Recursive call to appender Async
[07:08:56 ERROR]: Exception stopping the server
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:552) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:251) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:247) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:192) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:161) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at org.maxgamer.quickshop.util.reporter.error.RollbarErrorReporter.sendError(RollbarErrorReporter.java:180) ~[QuickShop-5.1.0.4-SNAPSHOT.jar:?]
        at org.maxgamer.quickshop.util.reporter.error.RollbarErrorReporter$GlobalExceptionFilter.isLoggable(RollbarErrorReporter.java:365) ~[QuickShop-5.1.0.4-SNAPSHOT.jar:?]
        at java.util.logging.Logger.log(Logger.java:966) ~[?:?]
        at java.util.logging.Logger.doLog(Logger.java:1007) ~[?:?]
        at java.util.logging.Logger.log(Logger.java:1118) ~[?:?]
        at org.bukkit.plugin.SimplePluginManager.handlePluginException(SimplePluginManager.java:585) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:539) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:514) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.disablePlugins(CraftServer.java:498) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1049) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:839) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1342) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.MinecraftServer$$Lambda$3973/0x0000000064039450.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Thread.java:884) ~[?:?]

**Comment by AdminHcat** [comment]
Build #2222 error

**Comment by Ghost-chu** [comment]
not recommmend to use SNAPSHOT

**Comment by sandtechnology** [comment]
Please use https://ci.codemc.io/job/PotatoCraft-Studio/job/QuickShop-Reremake-SNAPSHOT/2213/
